---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-demo-lva-io-v1-icecream
  failurePolicy: Fail
  name: vicecream.kb.io
  rules:
  - apiGroups:
    - demo.lva.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - icecreams
  sideEffects: None
