# permissions for end users to view icecreams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: icecream-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demooperator
    app.kubernetes.io/part-of: demooperator
    app.kubernetes.io/managed-by: kustomize
  name: icecream-viewer-role
rules:
- apiGroups:
  - demo.lva.io
  resources:
  - icecreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.lva.io
  resources:
  - icecreams/status
  verbs:
  - get
