# permissions for end users to edit lvavolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lvavolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demooperator
    app.kubernetes.io/part-of: demooperator
    app.kubernetes.io/managed-by: kustomize
  name: lvavolume-editor-role
rules:
- apiGroups:
  - demooperator.operator.caas-0002.beta.austrianopencloudcommunity.org
  resources:
  - lvavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demooperator.operator.caas-0002.beta.austrianopencloudcommunity.org
  resources:
  - lvavolumes/status
  verbs:
  - get
