---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demooperator.operator.caas-0002.beta.austrianopencloudcommunity.org
  resources:
  - lvavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demooperator.operator.caas-0002.beta.austrianopencloudcommunity.org
  resources:
  - lvavolumes/finalizers
  verbs:
  - update
- apiGroups:
  - demooperator.operator.caas-0002.beta.austrianopencloudcommunity.org
  resources:
  - lvavolumes/status
  verbs:
  - get
  - patch
  - update
