---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.lva.io
  resources:
  - icecreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.lva.io
  resources:
  - icecreams/finalizers
  verbs:
  - update
- apiGroups:
  - demo.lva.io
  resources:
  - icecreams/status
  verbs:
  - get
  - patch
  - update
